import os
import requests

BOT_TOKEN = os.environ["BOT_TOKEN"]
CHANNEL_ID = "@beshsomm"

def get_rate():
    url = "https://open.er-api.com/v6/latest/CNY"
    data = requests.get(url, timeout=20).json()
    rate = data["rates"]["UZS"]
    updated = data.get("time_last_update_utc", "Unknown")
    return rate, updated

def send_message(text):
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": CHANNEL_ID,
        "text": text
    }
    r = requests.post(url, data=payload, timeout=20)
    r.raise_for_status()

def main():
    rate, updated = get_rate()

    text = f"""💴 Курс юаня (CNY)

📊 Сегодня: rate = round(data["rates"]["UZS"])
🕒 Обновлено: {updated}

📦 Китай → Узбекистан
🚚 Доставка 13–16 дней

👉 @beshsomm
"""

    send_message(text)

if __name__ == "__main__":
    main()
